Italian Fiscal Code regex
bee-san/pyWhat pull request #243
Opened 2021-12-05 13:59 UTC by mavnt

**⚠ Pull Requests not made with this template will be automatically closed 🔥**

## Prerequisites
- [x] Have you read the documentation on contributing? https://github.com/bee-san/pyWhat/wiki/Adding-your-own-Regex

## Why do we need this pull request?
Regex for Italian fiscal code (https://en.wikipedia.org/wiki/Italian_fiscal_code).

## What [GitHub issues](https://github.com/bee-san/pyWhat/issues) does this fix?
None.

## Copy / paste of output

Please copy and paste the output of PyWhat with your new addition using an example that tests this addition below:

```console
$ pywhat "RSSMRA00A01H501C"
Matched on: RSSMRA00A01H501C
Name: Italian Fiscal Code
Description: https://en.wikipedia.org/wiki/Italian_fiscal_code
```

2021-12-05 16:50 UTC, bee-san approved these changes

2021-12-06 04:58 UTC, piatrashkakanstantinass requested changes

2021-12-06 04:58 UTC, piatrashkakanstantinass commented on pywhat/Data/regex.json
> +      "Description": "https://en.wikipedia.org/wiki/Italian_fiscal_code",
Remove the description. If a user want to know about the code, they can Google it.

2021-12-06 04:58 UTC, piatrashkakanstantinass commented on pywhat/Data/regex.json
> +      "Rarity": 0.7,
The rarity seems to be too high for me

2021-12-06 04:58 UTC, piatrashkakanstantinass commented on pywhat/Data/regex.json
> +         "Credentials"
Can you add `Identifiers` tag?

2021-12-06 04:58 UTC, piatrashkakanstantinass commented on fixtures/file
> +RSSMRA00A01H501C
Remove this. Fixture file is used for click tests and we do not want to slow down these.

2021-12-06 04:58 UTC, piatrashkakanstantinass commented on tests/test_click.py
> +    assert re.findall("Italian Fiscal Code", str(result.output))
Remove this. Check my comment on fixtures file.

2021-12-06 04:58 UTC, piatrashkakanstantinass commented
Also, please squash the commits.

2021-12-07 04:55 UTC, piatrashkakanstantinass approved these changes

2021-12-07 05:12 UTC, merged